---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - import_tasks: tasks/osx-custom.yml
      tags: ['custom']

    - import_tasks: tasks/docker.yml
      tags: ['custom']
