---
- name: Create Docker CLI plugins directory
  ansible.builtin.file:
    path: ~/.docker/cli-plugins
    state: directory
    mode: '0755'

- name: Symlink Docker Compose
  ansible.builtin.file:
    src: /opt/homebrew/opt/docker-compose/bin/docker-compose
    dest: ~/.docker/cli-plugins/docker-compose
    state: link
    force: yes

- name: Symlink Docker Buildx
  ansible.builtin.file:
    src: /opt/homebrew/opt/docker-buildx/bin/docker-buildx
    dest: ~/.docker/cli-plugins/docker-buildx
    state: link
    force: yes

- name: Create Colima VM for docker
  shell: colima start --cpu 4 --memory 4 --dns 1.1.1.1 --vm-type vz --mount-type virtiofs --vz-rosetta