---
- name: Symlink Docker Compose
  shell:
    - mkdir -p ~/.docker/cli-plugins
    - ln -sfn /opt/homebrew/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose

- name: Symlink Docker Buildx
  shell:
    - mkdir -p ~/.docker/cli-plugins
    - ln -sfn /opt/homebrew/opt/docker-buildx/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx
    - docker buildx install

- name: Create Colima (Qemu) VM for docker
  shell:
    - colima start --cpu 4 --memory 4 --dns 1.1.1.1 --vm-type vz --mount-type virtiofs 
    #--vz-rosetta still has problems
