---
- name: Check if pipx packages are already installed
  shell: pipx list --short
  register: pipx_list
  changed_when: false
  failed_when: false

- name: Install global pipx packages.
  shell: pipx install "{{ item.name | default(item) }}"
  loop: "{{ pipx_packages }}"
  when: 
    - pipx_packages is defined 
    - pipx_packages | length > 0
    - (item.name | default(item)) not in pipx_list.stdout
  register: pipx_result
