---
- name: Install global uv packages (with idempotency)
  shell: |
    PACKAGE_NAME="{{ item.name | default(item) }}"
    if uv tool list 2>/dev/null | grep -q "^${PACKAGE_NAME} "; then
      echo "Package ${PACKAGE_NAME} already installed"
    else
      echo "Installing ${PACKAGE_NAME}..."
      uv tool install "${PACKAGE_NAME}"
    fi
  loop: "{{ uv_packages }}"
  when: 
    - uv_packages is defined 
    - uv_packages | length > 0
  register: uv_result
  changed_when: '"Installing" in uv_result.stdout'
